# Sample docker-compose for testing and, with mods, production
version: '2.3'
services:
  ncwms:
    image: pcic/docker-ncwms:latest
    container_name: docker-ncwms-2.5.1-epsg
    ports:
      - "30780:8080"
    volumes:
      - type: bind
        source: /storage/data/projects/comp_support/ncwms/dev/test_sis_ncwms-2.5.1-snapshot/config.xml
        target: /usr/local/tomcat/.ncWMS2/config.xml
      - type: bind
        source: /storage/data
        target: /storage/data
        read_only: true
#     - type: bind
#       source: /storage/data/projects/comp_support/climate_explorer_data_prep
#       target: /storage/data/projects/comp_support/climate_explorer_data_prep
#       read_only: true
#     - type: bind
#       source: /storage/data/climate/downscale/CMIP5
#       target: /storage/data/climate/downscale/CMIP5
#       read_only: true
#     - type: bind
#       source: /storage/data/climate/downscale/BCCAQ2
#       target: /storage/data/climate/downscale/BCCAQ2
#       read_only: true
#     - type: bind
#       source: /storage/data/projects/dataportal/data
#       target: /storage/data/projects/dataportal/data
#       read_only: true
#     - type: bind
#       source: /storage/data/climate/PRISM/dataportal
#       target: /storage/data/climate/PRISM/dataportal
#       read_only: true
#     - type: bind
#       source: /storage/data/projects/hydrology/dataportal
#       target: /storage/data/projects/hydrology/dataportal
#       read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/pcex/new-ncWMS/2.4.2/tomcat-users.xml
        target: /usr/local/tomcat/conf/tomcat-users.xml
      - type: bind
        source: /storage/data/projects/comp_support/ncwms/dev/test_sis_ncwms-2.5.1-snapshot/ncWMS2-dir
        target: /usr/local/tomcat/.ncWMS2
#      - type: bind
#        source: /storage/data/projects/comp_support/ncwms/dev/test_sis_ncwms-2.5.1-snapshot/sis
#        target: /opt/sis
